//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#include "bldcdk.h"

//SI_SBIT(BTN0, SFR_P0, 2);
//#define BTN0_PRESSED (0)

////-----------------------------------------------------------------------------
//// PMATCH_ISR
////-----------------------------------------------------------------------------
////
//// PMATCH ISR Content goes here. Remember to clear flag bits:
////
////-----------------------------------------------------------------------------
//SI_INTERRUPT(PMATCH_ISR, PMATCH_IRQn)
//{
//	// Disable PMATCH interrupt until BTN0 is released.
//	EIE1 &= ~EIE1_EMAT__BMASK;
//}


